const { spawn } = require('child_process'); const path = require('path'); const fs = require('fs'); const os = require('os');
const root = path.resolve(__dirname, '..'); const puppeteer = require('puppeteer');
const PORT = 9660 + Math.floor(Math.random() * 30); const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'o2o-txt-'));
const env = { ...process.env, NODE_ENV: 'production', ONETOONE_DB_PATH: path.join(tmp, 'db.sqlite') };
delete env.ELECTRON_RUN_AS_NODE; delete env.ONETOONE_DIAG; delete env.VITE_DEV_SERVER_URL;
const app = spawn(path.join(root, 'node_modules', 'electron', 'dist', 'electron.exe'), ['.', `--remote-debugging-port=${PORT}`, `--user-data-dir=${path.join(tmp,'ud')}`], { cwd: root, env, stdio: 'pipe' });
(async () => {
  await new Promise((r) => setTimeout(r, 7000));
  const b = await puppeteer.connect({ browserURL: `http://127.0.0.1:${PORT}`, defaultViewport: null }); const page = (await b.pages())[0];
  await page.reload(); await new Promise((r) => setTimeout(r, 1500));
  const nome = `Txt ${Date.now().toString().slice(-4)}`;
  await page.waitForSelector('#btn-novo-atendido'); await page.click('#btn-novo-atendido');
  await page.waitForSelector('#input-nome'); await page.type('#input-nome', nome); await page.type('#input-contato', '11999998888');
  await page.click('#btn-salvar-atendido'); await page.waitForSelector('#input-busca-atendido');
  const sel = `tr[data-nome="${nome}"] button[id^="btn-ver-detalhes-"]`; await page.waitForSelector(sel); await page.click(sel);
  await page.waitForSelector('#btn-abrir-nova-sessao'); await page.click('#btn-abrir-nova-sessao');
  await page.waitForSelector('#input-titulo-sessao'); await page.type('#input-titulo-sessao', 'Txt');
  await page.click('#btn-confirmar-sessao'); await page.waitForSelector('#painel-sala-servidor');
  await page.waitForSelector('#btn-abrir-quadro-servidor'); await page.click('#btn-abrir-quadro-servidor');
  await page.waitForSelector('.upper-canvas'); await new Promise((r) => setTimeout(r, 900));
  const box = await page.$eval('.upper-canvas', (el) => { const r = el.getBoundingClientRect(); return { x: r.left, y: r.top }; });
  await page.click('#tool-text');
  await page.mouse.click(box.x + 150, box.y + 200); await new Promise((r) => setTimeout(r, 500));
  const editandoLogoApos = await page.evaluate(() => { const o = window.__whiteboardEngine.canvas.getActiveObject(); return { temAtivo: !!o, editando: !!(o && o.isEditing), ferramenta: window.__whiteboardEngine.activeTool }; });
  await page.keyboard.type('OiMundo'); await new Promise((r) => setTimeout(r, 400));
  await page.mouse.click(box.x + 700, box.y + 450); await new Promise((r) => setTimeout(r, 700));
  const textos = await page.evaluate(() => window.__whiteboardEngine.canvas.getObjects().filter((o) => o.type === 'IText' || o.type === 'i-text' || o.text !== undefined).map((o) => o.text));
  console.log('BRANCH:', require('child_process').execSync('git rev-parse --abbrev-ref HEAD').toString().trim());
  console.log('logo apos clicar com ferramenta texto:', JSON.stringify(editandoLogoApos));
  console.log('textos no canvas:', JSON.stringify(textos));
  console.log(textos.includes('OiMundo') ? 'RESULTADO: OK, digitacao funcionou' : 'RESULTADO: FALHA, digitacao NAO chegou no objeto');
  await b.disconnect(); app.kill(); process.exit(0);
})().catch((e) => { console.error(e); app.kill(); process.exit(2); });
